import { SubtitleTemplate } from '@/types/subtitle.types';

export const subtitleTemplates: SubtitleTemplate[] = [
  {
    id: 'interview',
    name: 'Interview / Dialogue',
    description: '2-line captions, 32 chars max per line. Great for interviews and conversations.',
    maxCharsPerLine: 32,
    defaultDuration: 3,
    icon: 'mic',
    entries: [
      {
        id: '1',
        sequenceNumber: 1,
        startTime: '00:00:01,000',
        endTime: '00:00:04,000',
        text: 'Speaker 1: Hello, welcome\nto the show today.',
      },
      {
        id: '2',
        sequenceNumber: 2,
        startTime: '00:00:05,000',
        endTime: '00:00:08,000',
        text: 'Speaker 2: Thank you for\nhaving me here.',
      },
      {
        id: '3',
        sequenceNumber: 3,
        startTime: '00:00:09,000',
        endTime: '00:00:12,000',
        text: 'Speaker 1: Let\'s start with\nyour background.',
      },
    ],
  },
  {
    id: 'tutorial',
    name: 'Tutorial / Educational',
    description: 'Longer duration, descriptive text. Perfect for educational content.',
    maxCharsPerLine: 45,
    defaultDuration: 5,
    icon: 'graduation-cap',
    entries: [
      {
        id: '1',
        sequenceNumber: 1,
        startTime: '00:00:01,000',
        endTime: '00:00:06,000',
        text: 'Welcome to this tutorial on subtitle creation.',
      },
      {
        id: '2',
        sequenceNumber: 2,
        startTime: '00:00:07,000',
        endTime: '00:00:12,000',
        text: 'First, we will cover the basics of SRT format.',
      },
      {
        id: '3',
        sequenceNumber: 3,
        startTime: '00:00:13,000',
        endTime: '00:00:18,000',
        text: 'Each subtitle entry has a sequence number,\ntimestamp, and text content.',
      },
    ],
  },
  {
    id: 'social',
    name: 'Social Media',
    description: 'Short, punchy captions. 1-2 seconds duration for fast-paced content.',
    maxCharsPerLine: 25,
    defaultDuration: 2,
    icon: 'share-2',
    entries: [
      {
        id: '1',
        sequenceNumber: 1,
        startTime: '00:00:00,500',
        endTime: '00:00:02,000',
        text: 'Check this out! 🔥',
      },
      {
        id: '2',
        sequenceNumber: 2,
        startTime: '00:00:02,500',
        endTime: '00:00:04,000',
        text: 'Wait for it...',
      },
      {
        id: '3',
        sequenceNumber: 3,
        startTime: '00:00:04,500',
        endTime: '00:00:06,000',
        text: 'Mind blown! 🤯',
      },
    ],
  },
  {
    id: 'movie',
    name: 'Movie / Film',
    description: 'Standard timing with proper formatting for cinematic content.',
    maxCharsPerLine: 40,
    defaultDuration: 3,
    icon: 'film',
    entries: [
      {
        id: '1',
        sequenceNumber: 1,
        startTime: '00:00:01,000',
        endTime: '00:00:04,000',
        text: 'In a world where anything is possible...',
      },
      {
        id: '2',
        sequenceNumber: 2,
        startTime: '00:00:05,000',
        endTime: '00:00:08,000',
        text: 'One person must rise above the rest.',
      },
      {
        id: '3',
        sequenceNumber: 3,
        startTime: '00:00:09,000',
        endTime: '00:00:12,000',
        text: 'This summer, prepare yourself\nfor the unexpected.',
      },
    ],
  },
  {
    id: 'custom',
    name: 'Custom / Blank',
    description: 'Start from scratch with your own settings.',
    maxCharsPerLine: 50,
    defaultDuration: 3,
    icon: 'edit',
    entries: [
      {
        id: '1',
        sequenceNumber: 1,
        startTime: '00:00:01,000',
        endTime: '00:00:04,000',
        text: 'Your subtitle text here',
      },
    ],
  },
];
